### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by asya-dukhan** [google-developer-training/basic-android-kotlin-compose-training-affirmations#2]
**Name of the Codelab or Codelab URL**

[[[Android Compose](https://developer.android.com/courses/android-basics-compose/course)](https://developer.android.com/courses/android-basics-compose/unit-3)](https://developer.android.com/courses/android-basics-compose/unit-3)

**Describe the problem**

ic_launcher_foreground.xml looks like a bell, but in example it should look like a flower, so it is probably the wrong file.

**In which lesson and step of the codelab can this issue be found?**
 Built a scrollable list. Change the App Icon + Step 5. Download new assets. 

**How to reproduce?**
By trying to add new image asset with this file

**Versions**

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: G1 Young Generation, G1 Old Generation
Registry: external.system.auto.import.disabled=true

2. What API level are you targeting?
 
**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by correabuscar** [comment]
So, the url for the text `Download ic_launcher_foreground.xml, which is the vector drawable for the foreground layer.` is wrong, as it points to: https://raw.githubusercontent.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/main/app/src/main/res/drawable-anydpi-v26/ic_launcher_foreground.xml
instead of to: https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/main/app/src/main/res/drawable/ic_launcher_foreground.xml
which is the file in this repo: https://github.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/blob/main/app/src/main/res/drawable/ic_launcher_foreground.xml
which I've tested to be the one seen in the step 11 Preview of https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#5

and also the text says `Download the following two new assets that enable you to create an adaptive icon for a Tip Calculator app.`

**Comment by a1danial** [comment]
Admittingly, its still confusing when you include icons for Tip Calculator. I'd recommend altering its content to match the course.

**Comment by osuleymanova** [comment]
Hello @asya-dukhan  ,

Thank you for reaching out to us and reporting the issue. The app name and  the assets were updated:

![Screen Shot 2022-12-01 at 2 26 38 PM](https://user-images.githubusercontent.com/86437155/205172778-3fe53af5-98b8-4d77-bb38-493427bd201c.png)
